FROM debian:13

RUN apt-get update
RUN apt-get upgrade -y

# curl for healthcheck
RUN apt install -y vim curl git perl cpanminus build-essential

# Perl modules
# for Crypt::Argon2
RUN apt install -y libssl-dev
# for Net::SSLeay
RUN apt install -y zlib1g-dev
# for Mojo::Pg
RUN apt install -y postgresql-client postgresql-server-dev-all

# run as root to write doc
RUN cpanm Carton

RUN useradd -ms /bin/bash webdev
USER webdev
WORKDIR /home/webdev

RUN git clone *your repo url* website

WORKDIR website

# to ensure the update of this image
RUN git pull

COPY --chown=webdev:webdev website.conf .

RUN carton install

EXPOSE 2000

# change localhost to your domain name
CMD ["/usr/local/bin/carton", "exec", "./script/website.pl", "daemon", "-l", "https://[::]:2000?cert=../tls/localhost/fullchain.pem&key=../tls/localhost/privkey.pem", "-m", "production"]
